feat: add support for using env variable `GLAZEWM_CONFIG_FILE` for config path
glzr-io/glazewm pull request #696
Opened 2024-08-27 12:17 UTC by nikitarevenco

Closes #689

2024-08-31 07:14 UTC, lars-berger requested changes

2024-08-31 07:14 UTC, lars-berger commented on packages/wm/src/user_config.rs
> +    let env_config_path = env::var("GLAZEWM_CONFIG_FILE").ok().map(PathBuf::from);
could we rename this to `GLAZEWM_CONFIG_PATH`?

2024-08-31 07:14 UTC, lars-berger commented on packages/wm/src/user_config.rs
> +        .or(env_config_path)
we could use `or_else` here so that the env var doesn't have to be unnecessarily evaluated

```rust
    let config_path = config_path
      .or_else(|| env::var("GLAZEWM_CONFIG_PATH").ok().map(PathBuf::from))
      .unwrap_or(default_config_path);
```

2024-08-31 07:14 UTC, lars-berger commented
Sweet, thanks for the PR 🙌

2024-09-01 18:27 UTC, nikitarevenco commented on packages/wm/src/user_config.rs
> +        .or(env_config_path)
Ok, yes that's a good idea! i added it

2024-09-01 18:27 UTC, nikitarevenco commented on packages/wm/src/user_config.rs
> +    let env_config_path = env::var("GLAZEWM_CONFIG_FILE").ok().map(PathBuf::from);
Sure

2024-09-01 18:34 UTC, nikitarevenco commented
> Sweet, thanks for the PR 🙌

Note: Instead of specifying `GLAZEWM_CONFIG_PATH`, which will state the *directory* in which the config file is found, how about we have `GLAZEWM_CONFIG_FILE` which will 

> Sweet, thanks for the PR 🙌

I also added a note to the readme on the new env variable

2024-09-16 08:35 UTC, merged

2024-09-16 08:35 UTC, lars-berger commented
Perfect thank you!