feat: add commands `set-tiling-direction-vertical` and `set-tiling-direction-horizontal`
glzr-io/glazewm pull request #702
Opened 2024-08-29 22:20 UTC by JonasWischeropp

I added the two commands `set-tiling-direction-vertical` and `set-tiling-direction-horizontal`
in order to be able to set the tiling direction faster and in the same way it is done in `i3wm`.
When using `toggle-tiling-direction` one always has to identify the current direction first.

Let me know what you think. Specially whether using `panic!` here is the right method:
https://github.com/JonasWischeropp/glazewm/blob/3c3fd07cd667c7e6165aa422d144e88ee0858af0/packages/wm/src/containers/commands/toggle_tiling_direction.rs#L110

Thank you for this amazing window manager.

2024-08-31 07:06 UTC, lars-berger requested changes

2024-08-31 07:06 UTC, lars-berger commented on packages/wm/src/containers/commands/toggle_tiling_direction.rs
> +}
can be simplified to:

```rust
  let direction_container = container
    .direction_container()
    .context("No direction container.")?;

  match direction_container.tiling_direction() == tiling_direction {
    true => Ok(()),
    false => toggle_tiling_direction(container, state, config)
  }
```

2024-08-31 07:06 UTC, lars-berger commented on packages/wm/src/containers/commands/toggle_tiling_direction.rs
> +  direction: TilingDirection,
rename `direction` -> `tiling_direction`

2024-08-31 07:06 UTC, lars-berger commented on packages/wm/src/app_command.rs
> +  SetTilingDirectionVertical,
create single `set-tiling-direction <TILING_DIRECTION>` command instead of two separate

2024-08-31 07:07 UTC, lars-berger commented
Thanks for the pr 🙌 was looking to get this added at some point

Added some minor fixups otherwise lgtm

2024-08-31 10:58 UTC, JonasWischeropp commented
Thank you for the feedback. I have adjusted the code acordingly.

2024-09-01 06:23 UTC, merged

2024-09-01 06:23 UTC, lars-berger commented
Awesome, thank you ❤️