feat: add new config `general.shutdown_commands` and `general.reload_commands` and shutdown/reload Zebar along side the WM
glzr-io/glazewm pull request #713
Opened 2024-09-05 14:21 UTC by JonasWischeropp

This PR addresses #650 and #646
I added two config entries that allow easy execution of commands at shutdown and restart similar to `general.startup_commands`.
|Config entry| Execution time|
|-|-|
| `general.shutdown_commands` | just before shutdown |
| `general.reload_commands` | after config has reloaded |

These are then used in the sample config to shutdown and reload Zebar.
```yaml
general:
  startup_commands: ['shell-exec %userprofile%/.glzr/zebar/start.bat']
  shutdown_commands: ['shell-exec taskkill /IM zebar.exe /F']
  reload_commands: [
    'shell-exec taskkill /IM zebar.exe /F',
    'shell-exec %userprofile%/.glzr/zebar/start.bat'
  ]
```

2024-09-07 14:51 UTC, vlad420 commented
Good One! This is necessary.

2024-09-16 08:31 UTC, lars-berger requested changes

2024-09-16 08:31 UTC, lars-berger commented on README.md
> +  # Commands to run after the WM config has reloaded.
add newlines in-between

2024-09-16 08:31 UTC, lars-berger commented on packages/wm/src/user_config.rs
> +  pub reload_commands: Vec<InvokeCommand>,
could we rename this to `config_reload_commands`?

2024-09-16 08:31 UTC, lars-berger commented on packages/wm/src/wm.rs
> +pub fn perform_commands(
belongs a bit better as a fn on `InvokeCommand`. rename to `run_multiple` and remove the `platform_sync` call (instead explicitly call `platform_sync` wherever it's used)

2024-09-16 08:31 UTC, lars-berger commented on packages/wm/src/wm.rs
> +  mut subject_container: Container,
declare a local variable for `subject_container` instead of making it mut

2024-09-16 08:33 UTC, lars-berger commented
Really well written, thanks for taking care of this 🙌 

Just a couple nitpicks, otherwise good to go

2024-09-16 15:41 UTC, JonasWischeropp commented
I have refactored the code.

2024-09-16 16:23 UTC, lars-berger approved these changes

2024-09-16 16:23 UTC, lars-berger commented
Sweet looks great 👌

2024-09-16 16:23 UTC, merged

2024-09-28 21:35 UTC, lars-berger commented
Hey @JonasWischeropp quick heads up - did some minor fixups in a follow-up pr at #742

didn't manage to get the Zebar config reload command to work (could be a change in Zebar v1 -> v2 that changed the behavior), so i'll remove that for now until a CLI command is added to Zebar for reloading

2024-09-28 21:36 UTC, lars-berger commented
BTW will get around to reviewing your new PR shortly 👌 Sorry about the wait

2025-02-08 10:36 UTC, AfzGit commented
> This PR addresses #650 and #646 I added two config entries that allow easy execution of commands at shutdown and restart similar to `general.startup_commands`.
> 
> Config entry	Execution time
> `general.shutdown_commands`	just before shutdown
> `general.reload_commands`	after config has reloaded
> These are then used in the sample config to shutdown and reload Zebar.
> 
> ```yaml
> general:
>   startup_commands: ['shell-exec %userprofile%/.glzr/zebar/start.bat']
>   shutdown_commands: ['shell-exec taskkill /IM zebar.exe /F']
>   reload_commands: [
>     'shell-exec taskkill /IM zebar.exe /F',
>     'shell-exec %userprofile%/.glzr/zebar/start.bat'
>   ]
> ```

The shutdown and startup commands for Zebar are run in parallel so sometimes Zebar is closed down when it starts. This solution works: https://github.com/glzr-io/glazewm/issues/646#issuecomment-2643219163