feat: add window transparency effect
glzr-io/glazewm pull request #864
Opened 2024-11-24 17:27 UTC by jackssrt

This PR adds a window transparency effect. The effect can be enabled in the window_effects config, or it can be manually invoked with an app command.

## Some UX concerns

Not enabling the effect in both the focused_windows and other_windows effect config will cause GlazeWM to just leave the transparency applied by the enabled one be.
If the user uses the app command to change the transparency, the window effect will override the manual transparency change the next time it updates.
Some users might not expect this behavior.

## Code architecture problem

I wrote a TODO comment about using saturating_sub_signed when it's stable. Since we use nightly, we can simply enable it, but I don't know if that's okay with everyone. Also, that would entail using a bigger int type, since i8 is between -128 and 128. Maybe it's best just to keep using a boolean for the sign? Perhaps we could use an enum somehow?
It would also be nice if we could write this once and then have every command use the same system for handling delta values.

2024-11-27 18:01 UTC, lars-berger requested changes

2024-11-27 18:01 UTC, lars-berger commented on packages/wm/src/common/transparency_value.rs
> +  pub delta_sign: bool,
could remove `delta_sign` (keeping `is_delta` as is) and store the amount as positive/negative. if the amount is positive, then it's a positive delta, otherwise it's negative

2024-11-30 20:15 UTC, lars-berger commented on resources/assets/sample-config.yaml
> +      transparency: '5%'
Got feedback from someone testing on Discord - it'd probs make more sense to invert this (e.g. `opacity: '70%'` = the window is 70% visible rather than 70% transparent). Otherwise seemed to work really well for them 🙌

2024-12-04 17:08 UTC, jackssrt commented on resources/assets/sample-config.yaml
> +      transparency: '5%'
The `set-transparency` command might be a bit confusing now, since it takes in an opacity value. Should I rename it to something like `set-opacity`?

2024-12-04 17:09 UTC, jackssrt commented on packages/wm/src/common/platform/native_window.rs
> +      // TODO: Use saturating_sub_signed when it's stable
Not applicable anymore.

2024-12-04 17:26 UTC, jackssrt commented
Git is confusing... Sorry!

2024-12-04 17:50 UTC, jackssrt commented on resources/assets/sample-config.yaml
> +      transparency: '5%'
Renamed it to `set-opacity`.

2025-01-10 14:32 UTC, lars-berger approved these changes

2025-01-10 14:33 UTC, merged

2025-01-10 14:37 UTC, lars-berger commented
Absolutely huge! Thanks a bunch with the help on this ❤️ Sorry about the long wait with getting this merged - will get out a new release with this included next week.

2025-01-23 12:15 UTC, jackssrt commented
Thanks for merging! And nice catch with the delta value being in the config, I didn't think of that...

2025-02-05 13:26 UTC, OmarDerwy commented
Wait, does this also mean I could reduce the opacity of a certain window using a key binding?